version: "3"
services:
  solr:
    build: .
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - scout
volumes:
  solr_data: {}
